# Generated by Django 5.0.4 on 2024-05-04 12:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chatsession',
            old_name='user_id',
            new_name='user',
        ),
    ]
